//
// ImagesURL.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImagesURL: Codable, JSONEncodable, Hashable {

    public var small: String?
    public var thumb: String?

    public init(small: String? = nil, thumb: String? = nil) {
        self.small = small
        self.thumb = thumb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case small
        case thumb
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(small, forKey: .small)
        try container.encodeIfPresent(thumb, forKey: .thumb)
    }
}

